// generated by src/routes/package.gen.ts

import type {Package_Json} from '@ryanatkn/gro/package_json.js';
import type {Src_Json} from '@ryanatkn/gro/src_json.js';

export const package_json = {
	name: 'spiderspace.org',
	version: '0.0.1',
	description: 'community website with a YouTube channel about building it',
	motto: 'weaving web community',
	glyph: '🕸️',
	logo: 'logo.svg',
	logo_alt: 'a galaxy full of twinkling star spiders',
	license: 'MIT',
	public: true,
	homepage: 'https://www.spiderspace.org/',
	repository: 'https://github.com/ryanatkn/spiderspace.org',
	author: {name: 'Ryan Atkinson', email: 'mail@ryanatkn.com', url: 'https://www.ryanatkn.com/'},
	bugs: 'https://github.com/ryanatkn/spiderspace.org/issues',
	funding: 'https://www.ryanatkn.com/funding',
	scripts: {
		start: 'gro dev',
		dev: 'gro dev',
		build: 'gro build',
		check: 'gro check',
		test: 'gro test',
		preview: 'vite preview',
		deploy: 'gro deploy',
	},
	type: 'module',
	engines: {node: '>=20.12'},
	devDependencies: {
		'@ryanatkn/belt': '^0.24.9',
		'@ryanatkn/eslint-config': '^0.4.2',
		'@ryanatkn/fuz': '^0.111.0',
		'@ryanatkn/gro': '^0.130.2',
		'@ryanatkn/moss': '^0.8.0',
		'@sveltejs/adapter-static': '^3.0.2',
		'@sveltejs/kit': '^2.5.18',
		'@sveltejs/vite-plugin-svelte': '^3.1.1',
		eslint: '^9.7.0',
		'eslint-plugin-svelte': '^2.42.0',
		prettier: '^3.3.3',
		'prettier-plugin-svelte': '^3.2.5',
		svelte: '^5.0.0-next.184',
		'svelte-check': '^3.8.4',
		tslib: '^2.6.3',
		typescript: '^5.5.3',
		'typescript-eslint': '^8.0.0-alpha.44',
		uvu: '^0.5.6',
	},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [{files: 'package.json', options: {useTabs: false}}],
	},
	sideEffects: ['**/*.css'],
	files: ['dist'],
} satisfies Package_Json;

export const src_json = {name: 'spiderspace.org', version: '0.0.1'} satisfies Src_Json;

// generated by src/routes/package.gen.ts
